### ISSUE TITLE
如何写 CVE patch 的页面图片挂了

### ISSUE THREAD

**Issue by pacoxu** [klts-io/website#34]
https://klts.io/zh/docs/addpatch/add-patch/

![image](https://user-images.githubusercontent.com/2010320/147731582-cd2f4823-5061-424e-bae9-ba859a735518.png)

**Comment by pacoxu** [comment]
![image](https://user-images.githubusercontent.com/2010320/147731722-db5b9e7c-f88b-461b-b87a-e24fa0812e21.png)
目前的位置

![image](https://user-images.githubusercontent.com/2010320/147731755-2f65a93a-b643-4062-8df0-fd536c36cdb1.png)
shi bu shi是不是应该放到这里

**Comment by wzshiming** [comment]
这是 hugo 目录层级的一个问题, 对于相对引用有层级会差一级 需要加上 `../` 文档应该减少这种图片的

**Comment by wzshiming** [comment]
@calvin0327
