### ISSUE TITLE
网页访问加速(中国)

### ISSUE THREAD

**Issue by yankay** [klts-io/website#46]
Github Page 在中国访问缓慢，有没有方法能够加速在中国境内的访问。建议方法：

1. 通过 DNS 配置 分流 中国 和 境外的流量
2. 对于中国的流量 通过 CDN 或者 专线的方法访问。
  * 如果是 CDN 的方法，缓存刷新是个问题。可能需要通过 gtihub action 来手动刷缓存。对于 HTTPS，CDN 一般不支持 letsencrypt 证书。需要购买证书。
  * 如果是专线方方法，费用较高。但是如果流量不大，还是可以接受的。

如果这个方案通用，可以适用于 其他githubpage 项目，效果更佳。:-)

**Comment by wzshiming** [comment]
Done
